name: "Terraform CI"

# on:
#   pull_request:

on:
  push:
    branches:
      - main
    # paths:
    #   - 'environments/dev/**'
    #   - 'modules/**'

permissions:
  issues: write
  pull-requests: write


jobs:
  network:
    uses: ./.github/workflows/terraform_actions.yml
    with:
      directory: environments/dev/network
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  security:
    needs: network
    uses: ./.github/workflows/terraform_actions.yml
    with:
      directory: environments/dev/security
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  compute:
    needs: security
    uses: ./.github/workflows/terraform_actions.yml
    with:
      directory: environments/dev/compute
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  lb:
    needs: compute
    uses: ./.github/workflows/terraform_actions.yml
    with:
      directory: environments/dev/lb
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
